/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileChooser.java
 *
 * Created on Dec 13, 2009, 11:50:45 PM
 */

package pdfmerger;

import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import org.apache.pdfbox.util.ExtensionFileFilter;

/**
 *
 * @author Ryan
 */
public class FileChooserMultiFiles extends javax.swing.JFrame {

    Preferences prefsRoot;
    Preferences prefs;
    GUIFrame2 parent;
    /** Creates new form FileChooser */
    public FileChooserMultiFiles(GUIFrame2 parent) {
        prefsRoot = Preferences.userRoot();
        prefs = prefsRoot.node(FileChooserMultiFiles.class.getName());
        this.parent = parent;
        initComponents();
        FileFilter[] filters = jFileChooser1.getChoosableFileFilters();
        for(FileFilter filter : filters)
            jFileChooser1.removeChoosableFileFilter(filter);
        jFileChooser1.setMultiSelectionEnabled(true);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser1.addChoosableFileFilter(new ExtensionFileFilter(new String[]{"pdf"}, "PDF Files"));
        String currDir = prefs.get("currDir", "");
        if(!currDir.equals(""))
            jFileChooser1.setCurrentDirectory(new File(currDir));
        //jFileChooser1.setCurrentDirectory(defaultDir == null || defaultDir.trim() == null || defaultDir.trim().isEmpty() ? null : new File(defaultDir.trim()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jFileChooser1.setFileSelectionMode(jFileChooser1.DIRECTORIES_ONLY);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        parent.addFiles(jFileChooser1.getSelectedFiles());
        prefs.put("currDir", jFileChooser1.getCurrentDirectory().getPath());
        this.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}
